version: '3'

services:
  app:
    build: .
    container_name: mthink
    ports:
      - "8000:80"
    restart: unless-stopped
    networks:
      - mindmap_network

networks:
  mindmap_network:
    driver: bridge